services:
  enjoy-the-moment:
    container_name: enjoy_the_moment_node
    build: .
    command: npm run start
    restart: always
    ports:
      - 8015:8015
    environment:
      - NODE_ENV=prod
